import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { canonicalBalances, leafHashHex } from "./verify";
import { lpmap, reportDigestHex } from "./report";

/**
 * Differential vectors (SPEC §1–§3, §8.1), generated by the Rust producer and
 * recomputed here.
 *
 * The §6 golden vectors are three hand-written cases with ASCII asset names,
 * which is precisely why this implementation could sort keys by UTF-16 code
 * units for months without anything noticing — every published vector agreed
 * under both orderings.
 *
 * These 200 are generated over names chosen to break assumptions: astral
 * codepoints, the private-use block, the `:` and `|` that §2's join uses as
 * delimiters, and names differing only past a shared prefix. A divergence in
 * ordering, encoding, or canonicalisation now fails here rather than in one
 * venue's browser.
 */
const vectors = JSON.parse(
  readFileSync(fileURLToPath(new URL("../../../conformance/cross-vectors.json", import.meta.url)), "utf8")
);

describe("cross-implementation differential vectors", () => {
  it("is a corpus worth running", () => {
    expect(vectors.format_version).toBe("canton-solvency-cross-vectors-v1");
    expect(vectors.vectors.length).toBeGreaterThanOrEqual(100);
    // If every asset name were ASCII the corpus would be testing nothing the
    // golden vectors do not already cover.
    const nonAscii = vectors.vectors.filter((v: any) =>
      Object.keys(v.balances).some((a) => /[^\x20-\x7e]/.test(a))
    );
    expect(nonAscii.length).toBeGreaterThan(20);
    expect(vectors.reports.length).toBeGreaterThanOrEqual(40);
  });

  it("reproduces every canonical serialization", async () => {
    for (const v of vectors.vectors) {
      expect(canonicalBalances(v.balances), `canonical for ${v.user_id}`).toBe(v.canonical);
    }
  });

  it("reproduces every leaf hash", async () => {
    for (const v of vectors.vectors) {
      expect(await leafHashHex(v.salt, v.user_id, v.balances), `leaf for ${v.user_id}`).toBe(
        v.leaf_hash
      );
    }
  });

  it("reproduces every report digest", async () => {
    // The §8.2 preimage is what the signature covers. If the two
    // implementations disagreed here, every cross-implementation signature
    // check would fail — not one leaf.
    for (const entry of vectors.reports) {
      expect(
        await reportDigestHex(entry.report),
        `digest for ${entry.report.publisher}`
      ).toBe(entry.report_digest);
    }
  });

  it("reproduces every length-prefixed map", async () => {
    for (const v of vectors.vectors) {
      const hex = [...lpmap(v.balances)].map((b) => b.toString(16).padStart(2, "0")).join("");
      expect(hex, `lpmap for ${v.user_id}`).toBe(v.lpmap);
    }
  });
});
